### ISSUE TITLE
Highlights in code blocks can't be seen

### ISSUE THREAD

**Issue by catkins** [tconbeer/harlequin-web#15]
First off, love this! Saw it pop up on the DuckDB discord 🎨 

Small accessibility feedback -  the docs site is gorgeous and I love the yellow/pink theme, but highlighting the code block to copy it doesn't appear to have a visible highlight. 

<img width="787" alt="CleanShot 2023-09-20 at 10 23 50@2x" src="https://github.com/tconbeer/harlequin-web/assets/2272833/e94d94cf-ca85-4557-af1e-9df7e7aedc06">

I'm not the best with CSS to suggest a specific fix, but it looks like the overridden highlight colour on the normal text is applying to the `pre` blocks too but is the same colour as the background.

<img width="313" alt="CleanShot 2023-09-20 at 10 26 40@2x" src="https://github.com/tconbeer/harlequin-web/assets/2272833/80c02e0f-3cd9-4883-b793-4bdcb558794a">

Machine: Chrome 116 Arm64 / macOS Ventura

**Comment by tconbeer** [comment]
Thanks for the issue! I didn't think about that. Should be able to use a different color in the code blocks
